"""
=========================================================
Claus Incident Response Toolkit (CIRT)

HTML Report Exporter

Creates a professional forensic HTML report from
collected evidence.

Author : Claudias Musavini Misiko
Version: 1.0.0
=========================================================
"""

from pathlib import Path
from datetime import datetime

from logger import logger


# ==========================================================
# HTML Helper Functions
# ==========================================================

def html_header(title="Claus Incident Response Toolkit"):

    """
    Builds the HTML document header.
    """

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return f"""<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<meta name="viewport"
      content="width=device-width, initial-scale=1.0">

<title>{title}</title>

<style>

body {{

    background:#f5f7fa;

    font-family:Arial,Helvetica,sans-serif;

    color:#222;

    margin:40px;

}}

.container {{

    max-width:1200px;

    margin:auto;

}}

.card {{

    background:white;

    margin-bottom:20px;

    padding:20px;

    border-radius:10px;

    box-shadow:0 2px 8px rgba(0,0,0,.1);

}}

table {{

    width:100%;

    border-collapse:collapse;

}}

table th {{

    background:#1f4e79;

    color:white;

    padding:10px;

}}

table td {{

    padding:8px;

    border-bottom:1px solid #ddd;

}}

h1 {{

    color:#1f4e79;

}}

h2 {{

    color:#2d6a4f;

}}

.footer {{

    margin-top:40px;

    color:gray;

    font-size:13px;

}}

pre {{

    white-space:pre-wrap;

    word-wrap:break-word;

}}

</style>

</head>

<body>

<div class="container">

<div class="card">

<h1>🛡 Claus Incident Response Toolkit</h1>

<p>

<strong>Incident Report</strong>

</p>

<p>

Generated:

<strong>{timestamp}</strong>

</p>

</div>
"""
# ==========================================================
# HTML Section Builders
# ==========================================================

def html_table(title, data):
    """
    Create an HTML table from a dictionary.
    """

    html = f"""
<div class="card">

<h2>{title}</h2>

<table>

<tr>

<th>Field</th>

<th>Value</th>

</tr>
"""

    for key, value in data.items():

        html += f"""
<tr>

<td><strong>{key}</strong></td>

<td>{value}</td>

</tr>
"""

    html += """
</table>

</div>
"""

    return html


# ==========================================================

def html_list(title, items):
    """
    Create an HTML list section.
    """

    html = f"""
<div class="card">

<h2>{title}</h2>

<ul>
"""

    if not items:

        html += "<li>No data collected.</li>"

    else:

        for item in items:

            html += f"<li>{item}</li>"

    html += """
</ul>

</div>
"""

    return html


# ==========================================================

def html_preformatted(title, items):
    """
    Display long command output using PRE formatting.
    """

    html = f"""
<div class="card">

<h2>{title}</h2>

<pre>
"""

    if items:

        if isinstance(items, list):

            html += "\n".join(str(i) for i in items)

        else:

            html += str(items)

    else:

        html += "No data collected."

    html += """
</pre>

</div>
"""

    return html


# ==========================================================

def html_footer():
    """
    Build HTML footer.
    """

    return """
<div class="footer">

<hr>

<p>

Generated by
<strong>Claus Incident Response Toolkit (CIRT)</strong>

</p>

<p>

Version 1.0.0

</p>

</div>

</div>

</body>

</html>
"""
# ==========================================================
# HTML Report Generator
# ==========================================================

def generate_html_report(evidence, output_directory):
    """
    Generate a professional HTML incident response report.

    Parameters
    ----------
    evidence : dict
        Collected forensic evidence.

    output_directory : str | Path
        Directory where the report will be written.

    Returns
    -------
    pathlib.Path
        Path to the generated HTML report.
    """

    logger.info("Generating HTML report...")

    output_directory = Path(output_directory)
    output_directory.mkdir(parents=True, exist_ok=True)

    report_file = output_directory / "report.html"

    html = html_header()

    # ------------------------------------------------------
    # System Information
    # ------------------------------------------------------

    if "system_information" in evidence:

        html += html_table(
            "System Information",
            evidence["system_information"],
        )

    # ------------------------------------------------------
    # Logged-in Users
    # ------------------------------------------------------

    if "logged_in_users" in evidence:

        html += html_list(
            "Logged-in Users",
            evidence["logged_in_users"],
        )

    # ------------------------------------------------------
    # Uptime
    # ------------------------------------------------------

    if "uptime" in evidence:

        html += html_preformatted(
            "System Uptime",
            evidence["uptime"],
        )

    # ------------------------------------------------------
    # Running Processes
    # ------------------------------------------------------

    if "running_processes" in evidence:

        html += html_preformatted(
            "Running Processes",
            evidence["running_processes"],
        )

    # ------------------------------------------------------
    # Listening Ports
    # ------------------------------------------------------

    if "listening_ports" in evidence:

        html += html_preformatted(
            "Listening Ports",
            evidence["listening_ports"],
        )

    # ------------------------------------------------------
    # Network Connections
    # ------------------------------------------------------

    if "network_connections" in evidence:

        html += html_preformatted(
            "Network Connections",
            evidence["network_connections"],
        )

    # ------------------------------------------------------
    # Running Services
    # ------------------------------------------------------

    if "running_services" in evidence:

        html += html_preformatted(
            "Running Services",
            evidence["running_services"],
        )

    # ------------------------------------------------------
    # Disk Usage
    # ------------------------------------------------------

    if "disk_usage" in evidence:

        html += html_preformatted(
            "Disk Usage",
            evidence["disk_usage"],
        )

    # ------------------------------------------------------
    # Memory Usage
    # ------------------------------------------------------

    if "memory_usage" in evidence:

        html += html_preformatted(
            "Memory Usage",
            evidence["memory_usage"],
        )

    # ------------------------------------------------------
    # Mounted File Systems
    # ------------------------------------------------------

    if "mounted_filesystems" in evidence:

        html += html_preformatted(
            "Mounted File Systems",
            evidence["mounted_filesystems"],
        )

    # ------------------------------------------------------
    # Network Interfaces
    # ------------------------------------------------------

    if "network_interfaces" in evidence:

        html += html_preformatted(
            "Network Interfaces",
            evidence["network_interfaces"],
        )

    # ------------------------------------------------------
    # Routing Table
    # ------------------------------------------------------

    if "routing_table" in evidence:

        html += html_preformatted(
            "Routing Table",
            evidence["routing_table"],
        )

    html += html_footer()

    with open(
        report_file,
        "w",
        encoding="utf-8",
    ) as report:

        report.write(html)

    logger.info(
        "HTML report written to %s",
        report_file,
    )

    return report_file


# ==========================================================
# Standalone Test
# ==========================================================

if __name__ == "__main__":

    sample = {

        "system_information": {
            "hostname": "cirt-lab",
            "operating_system": "Ubuntu Linux",
            "current_user": "claus",
            "timestamp": "2026-07-18 12:00:00",
        },

        "logged_in_users": [
            "claus",
        ],

        "uptime": "2 days, 5 hours",

        "running_processes": [
            "systemd",
            "python",
            "sshd",
        ],

        "listening_ports": [
            "22/tcp",
            "80/tcp",
            "443/tcp",
        ],

        "network_connections": [
            "TCP 127.0.0.1:22",
        ],

        "running_services": [
            "ssh.service",
            "NetworkManager.service",
        ],

        "disk_usage": [
            "/dev/sda1 35%",
        ],

        "memory_usage": [
            "RAM: 6GB / 16GB",
        ],

        "mounted_filesystems": [
            "/",
            "/boot",
        ],

        "network_interfaces": [
            "eth0",
            "lo",
        ],

        "routing_table": [
            "default via 192.168.1.1",
        ],

    }

    report = generate_html_report(
        sample,
        "reports",
    )

    print()

    print("=" * 60)
    print("HTML REPORT CREATED")
    print("=" * 60)
    print(report)
    print("=" * 60)
